

export const IMG_LIST_REQUEST = 'IMG_LIST_REQUEST';
export const IMG_LIST_SUCCESS = 'IMG_LIST_SUCCESS';
export const IMG_LIST_FAIL = 'IMG_LIST_FAIL';

export const IMG_DETAILS_REQUEST = 'IMG_DETAILS_REQUEST';
export const IMG_DETAILS_SUCCESS = 'IMG_DETAILS_SUCCESS';
export const IMG_DETAILS_FAIL = 'IMG_DETAILS_FAIL';

export const IMG_SAVE_REQUEST = 'IMG_SAVE_REQUEST';
export const IMG_SAVE_SUCCESS = 'IMG_SAVE_SUCCESS';
export const IMG_SAVE_FAIL = 'IMG_SAVE_FAIL';

export const IMG_DELETE_REQUEST = 'IMG_DELETE_REQUEST';
export const IMG_DELETE_SUCCESS = 'IMG_DELETE_SUCCESS';
export const IMG_DELETE_FAIL = 'IMG_DELETE_FAIL';