export const ORDER_NOTE_CREATE_REQUEST = 'ORDER_NOTE_CREATE_REQUEST';
export const ORDER_NOTE_CREATE_SUCCESS = 'ORDER_NOTE_CREATE_SUCCESS';
export const ORDER_NOTE_CREATE_FAIL = 'ORDER_NOTE_CREATE_FAIL';

export const ORDER_NOTE_DETAILS_REQUEST = 'ORDER_NOTE_DETAILS_REQUEST';
export const ORDER_NOTE_DETAILS_SUCCESS = 'ORDER_NOTE_DETAILS_SUCCESS';
export const ORDER_NOTE_DETAILS_FAIL = 'ORDER_NOTE_DETAILS_FAIL';

export const MY_ORDER_NOTE_LIST_REQUEST = 'MY_ORDER_NOTE_LIST_REQUEST';
export const MY_ORDER_NOTE_LIST_SUCCESS = 'MY_ORDER_NOTE_LIST_SUCCESS';
export const MY_ORDER_NOTE_LIST_FAIL = 'MY_ORDER_NOTE_LIST_FAIL';

export const ORDER_NOTE_LIST_REQUEST = 'ORDER_NOTE_LIST_REQUEST';
export const ORDER_NOTE_LIST_SUCCESS = 'ORDER_NOTE_LIST_SUCCESS';
export const ORDER_NOTE_LIST_FAIL = 'ORDER_NOTE_LIST_FAIL';

export const ORDER_NOTE_PAY_REQUEST = 'ORDER_NOTE_PAY_REQUEST';
export const ORDER_NOTE_PAY_SUCCESS = 'ORDER_NOTE_PAY_SUCCESS';
export const ORDER_NOTE_PAY_FAIL = 'ORDER_NOTE_PAY_FAIL';

export const ORDER_NOTE_DELETE_REQUEST = 'ORDER_NOTE_DELETE_REQUEST';
export const ORDER_NOTE_DELETE_SUCCESS = 'ORDER_NOTE_DELETE_SUCCESS';
export const ORDER_NOTE_DELETE_FAIL = 'ORDER_NOTE_DELETE_FAIL';